In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('cereal.csv')
df

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0       6     280        25      3     1.0  0.33  68.402973  
1     8.0       8     135         0      3     1.0  1.00  33.983679  
2     7.0       5     320        25      3     1.0  0.33  59.425505  
3     8.0       0     330        25      3     1.0  0.50  93.704912  
4    14.0       8      -1        25      3     1.0  0.75  34.384843  
..    ...     ...     ...       ...    ...     ...   ...        ...  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

In [3]:
import matplotlib.pyplot as plt

plt.hist(df['sugars'],ec="r",color="green")
plt.hist(df['vitamins'])
plt.xlabel('sugars')
plt.ylabel('vitamins')
plt.show()


In [4]:
dict_mfr = {'N': 'Nabisco',
            'Q': 'Quaker Oats',
            'K': 'Kelloggs',
            'R': 'Raslston Purina',
            'G': 'General Mills',
            'P': 'Post',
            'A': 'American Home Foods Products'}
df["manufactures"] = [dict_mfr[mfr] for mfr in df["mfr"]]
df

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  \
0     5.0       6     280        25      3     1.0  0.33  68.402973   
1     8.0       8     135         0      3     1.0  1.00  33.983679   
2     7.0       5     320        25      3     1.0  0.33  59.425505   
3     8.0       0     330        25      3     1.0  0.50  93.704912   
4    14.0       8      -1        25      3     1.0  0.75  34.384843   
..    ...     ...     ...       ...    ...     ...   ...        ...   
72   21.0       3      60        25      3     1.0  0.75  39.106174   
73   13.0      12      25        25      2     1.0  1.00  27.753301   
74   17.0       3     115        25      1     1.0  0.67  49.787445   
75   17.0       3     110        25      1     1.0  1.00  51.592193   
76   16.0       8      60        25      1     1.0  0.75  36.187559   

       manufactures  
0           Nabisco  
1       Quaker Oats  
2          Kelloggs  
3          Kelloggs  
4   Raslston Purina  
..              ...  
72    General Mills  
73    General Mills  
74  Raslston Purina  
75    General Mills  
76    General Mills  

[77 rows x 17 columns]

In [5]:
import matplotlib.pyplot as plt
df["manufactures"] = [dict_mfr[mfr] for mfr in df["mfr"]]
grouped_mfr = df.groupby(["manufactures"], as_index=False).count()
x = grouped_mfr["manufactures"]
y = grouped_mfr["mfr"]

plt.bar(x, y)
plt.setp(plt.gca().get_xticklabels(), rotation=90, horizontalalignment='right')
plt.xlabel("Manufactureres")
plt.ylabel("Count")
plt.title("number of cereals manufactured by Manufactures")
plt.show()

In [6]:
x=df.iloc[:,3:15].values
x

array([[ 7.00e+01,  4.00e+00,  1.00e+00,  1.30e+02,  1.00e+01,  5.00e+00,
         6.00e+00,  2.80e+02,  2.50e+01,  3.00e+00,  1.00e+00,  3.30e-01],
       [ 1.20e+02,  3.00e+00,  5.00e+00,  1.50e+01,  2.00e+00,  8.00e+00,
         8.00e+00,  1.35e+02,  0.00e+00,  3.00e+00,  1.00e+00,  1.00e+00],
       [ 7.00e+01,  4.00e+00,  1.00e+00,  2.60e+02,  9.00e+00,  7.00e+00,
         5.00e+00,  3.20e+02,  2.50e+01,  3.00e+00,  1.00e+00,  3.30e-01],
       [ 5.00e+01,  4.00e+00,  0.00e+00,  1.40e+02,  1.40e+01,  8.00e+00,
         0.00e+00,  3.30e+02,  2.50e+01,  3.00e+00,  1.00e+00,  5.00e-01],
       [ 1.10e+02,  2.00e+00,  2.00e+00,  2.00e+02,  1.00e+00,  1.40e+01,
         8.00e+00, -1.00e+00,  2.50e+01,  3.00e+00,  1.00e+00,  7.50e-01],
       [ 1.10e+02,  2.00e+00,  2.00e+00,  1.80e+02,  1.50e+00,  1.05e+01,
         1.00e+01,  7.00e+01,  2.50e+01,  1.00e+00,  1.00e+00,  7.50e-01],
       [ 1.10e+02,  2.00e+00,  0.00e+00,  1.25e+02,  1.00e+00,  1.10e+01,
         1.40e+01,  3.00e+01,  2

In [7]:
y=df.iloc[:,15].values
y

array([68.402973, 33.983679, 59.425505, 93.704912, 34.384843, 29.509541,
       33.174094, 37.038562, 49.120253, 53.313813, 18.042851, 50.764999,
       19.823573, 40.400208, 22.736446, 41.445019, 45.863324, 35.782791,
       22.396513, 40.448772, 64.533816, 46.895644, 36.176196, 44.330856,
       32.207582, 31.435973, 58.345141, 40.917047, 41.015492, 28.025765,
       35.252444, 23.804043, 52.076897, 53.371007, 45.811716, 21.871292,
       31.072217, 28.742414, 36.523683, 36.471512, 39.241114, 45.328074,
       26.734515, 54.850917, 37.136863, 34.139765, 30.313351, 40.105965,
       29.924285, 40.69232 , 59.642837, 30.450843, 37.840594, 41.50354 ,
       60.756112, 63.005645, 49.511874, 50.828392, 39.259197, 39.7034  ,
       55.333142, 41.998933, 40.560159, 68.235885, 74.472949, 72.801787,
       31.230054, 53.131324, 59.363993, 38.839746, 28.592785, 46.658844,
       39.106174, 27.753301, 49.787445, 51.592193, 36.187559])

In [9]:
from sklearn.preprocessing import StandardScaler
obj=StandardScaler()
x=obj.fit_transform(x)
x

array([[-1.90539669e+00,  1.33731939e+00, -1.29881083e-02,
        -3.56305633e-01,  3.31443928e+00, -2.25763865e+00,
        -2.08807273e-01,  2.59694789e+00, -1.46270130e-01,
         9.57813297e-01, -1.98067464e-01, -2.12387042e+00],
       [ 6.77623471e-01,  4.17912310e-01,  3.98734926e+00,
        -1.73708742e+00, -6.41716689e-02, -1.55193563e+00,
         2.44098644e-01,  5.49573000e-01, -1.27255013e+00,
         9.57813297e-01, -1.98067464e-01,  7.74052748e-01],
       [-1.90539669e+00,  1.33731939e+00, -1.29881083e-02,
         1.20457813e+00,  2.89211291e+00, -1.78716997e+00,
        -4.35260232e-01,  3.16174096e+00, -1.46270130e-01,
         9.57813297e-01, -1.98067464e-01, -2.12387042e+00],
       [-2.93860476e+00,  1.33731939e+00, -1.01307245e+00,
        -2.36237652e-01,  5.00374475e+00, -1.55193563e+00,
        -1.56752502e+00,  3.30293923e+00, -1.46270130e-01,
         9.57813297e-01, -1.98067464e-01, -1.38857648e+00],
       [ 1.61019439e-01, -5.01494772e-01,  9.8709623

In [10]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
print(x_train,x_test,y_train,y_test)


[[ 1.61019439e-01 -5.01494772e-01  9.87096234e-01  4.84170237e-01
  -4.86498037e-01 -1.40529604e-01  2.44098644e-01 -1.37072345e+00
  -1.46270130e-01  9.57813297e-01 -1.98067464e-01 -3.07261867e-01]
 [ 6.77623471e-01  4.17912310e-01  9.87096234e-01  3.89831109e-03
   1.20280744e+00 -6.10998280e-01  6.97004561e-01  1.46736174e+00
  -1.46270130e-01  9.57813297e-01  1.47421266e+00 -6.53282544e-01]
 [-3.55584594e-01  4.17912310e-01  9.87096234e-01 -2.36237652e-01
   1.46991515e-01 -9.63849787e-01  2.44098644e-01  6.20172134e-01
  -1.46270130e-01  9.57813297e-01 -1.98067464e-01 -1.38857648e+00]
 [-3.55584594e-01 -5.01494772e-01 -1.01307245e+00 -1.37688348e+00
  -9.08824405e-01 -8.46232618e-01  1.82926935e+00 -7.91810548e-01
  -1.46270130e-01 -1.46027273e+00 -1.98067464e-01  2.55021733e-01]
 [-2.93860476e+00  1.33731939e+00 -1.01307245e+00 -2.36237652e-01
   5.00374475e+00 -1.55193563e+00 -1.56752502e+00  3.30293923e+00
  -1.46270130e-01  9.57813297e-01 -1.98067464e-01 -1.38857648e+00]
 [ 1.

In [11]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
lr_output=lr.predict(x_test)
lr_output

array([74.47294875, 41.44501953, 46.65884398, 59.42550457, 60.75611164,
       39.25919737, 38.83974524, 40.69232043, 22.39651289, 28.59278461,
       49.51187429, 50.82839145, 34.13976442, 45.81171569, 33.17409445,
       33.98367876, 36.18755876, 30.31335109, 41.01549189, 68.40297266])

In [12]:
from sklearn.metrics import mean_squared_error
mean_squared_error(lr_output,y_test)

1.4978983021251507e-13